FROM library/python:3.9.6-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY requirements.txt /app/
COPY . /app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 8000

CMD  python manage.py makemigrations \
  && python manage.py migrate \
  && python manage.py loaddata init_data.json \
  && python manage.py runserver 0.0.0.0:8000



