version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    #image: krassy19/cbirds
    build: .
    container_name: web
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py loaddata init_data.json && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /static:/static
    expose:
      - "8000"

  db:
    image: postgres:14-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=krassy
      - APP_DB_PASS=19
      - APP_DB_NAME=krassydb
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d/
    ports:
        - 5432:5432