version: "2"
services:
  web:
    image: krassy19/birdsdb
    container_name: web
    depends_on:
      - db
    volumes:
      - .:/app
      - /static:/static
    expose:
      - "8000"

  db:
    image: krassy19/db
    restart: always
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql
    ports:
        - 5432:5432
