apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: "krassydb"
  POSTGRES_USER: "krassy"
env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: POSTGRES_PASSWORD
