apiVersion: v1
kind: Secret
metadata:
  name: postgress
type: Opaque
data:
  APP_DB_USER:   {{ .Values.APP_DB_USER | b64enc | quote }}
  APP_DB_PASS:   {{ .Values.APP_DB_PASS | b64enc | quote }}
  APP_DB_NAME:   {{ .Values.APP_DB_NAME | b64enc | quote }}
  DATABASE_HOST: {{ .Values.DATABASE_HOST | b64enc | quote }}