apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    name: db
  type: ClusterIP
  selector:
    app: postgres
