apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
    myapp: birds
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: krassy19/db
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim


