apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: krassy19/birdsdb
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        env:
        - name: APP_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgress
              key: APP_DB_USER
        - name: APP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgress
              key: APP_DB_PASS
        - name: APP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgress
              key: APP_DB_NAME

