apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: krassy19/cbirds:latest
        imagePullPolicy: "Always"
        name: web
        ports:
        - containerPort: 8000
      restartPolicy: Always
      envFrom:
      - ConfigMapRef:
          name: postgres-configuration
serviceName: web